all:
  hosts:
    node-0:
      ansible_host: 192.168.50.103
      ip: 192.168.50.103
      access_ip: 192.168.50.103
  children:
    kube_control_plane:
      hosts:
        node-0:
    kube_node:
      hosts:
        node-0:
    etcd:
      hosts:
        node-0:
    calico_rr:
      hosts: {}
